name: Fetch Netflix verify to latest version

on:
  workflow_dispatch:
  schedule:
    - cron: "00 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Fetch Netfilx verify latest version
        run: |
          rm -f files/netflix-verify/nf-linux-amd64 files/netflix-verify/nf-linux-arm64 files/netflix-verify/nf-linux-s390x files/netflix-verify/nfverify-fetchlog.txt
          actions_date=$(date)
          repo_last_ver=$(curl -Ls "https://api.github.com/repos/sjlleo/netflix-verify/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          wget https://github.com/sjlleo/netflix-verify/releases/download/$repo_last_ver/nf_linux_amd64 -O files/netflix-verify/nf-linux-amd64
          wget https://github.com/sjlleo/netflix-verify/releases/download/$repo_last_ver/nf_linux_arm64 -O files/netflix-verify/nf-linux-arm64
          wget https://github.com/sjlleo/netflix-verify/releases/download/$repo_last_ver/nf_linux_s390x -O files/netflix-verify/nf-linux-s390x
          cat <<EOF > files/netflix-verify/nfverify-fetchlog.txt
          # Netfilx verify fetch log generated by GitHub Actions
          Last Version: $repo_last_ver
          Fetch Date: $actions_date
          EOF
      - name: Upload to GitHub
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "CI: Auto fetch Netflix verify at $(date +"%m-%d %H:%M")"
          git push
      - name: Refresh Jsdelivr cache
        run: |
          curl https://purge.jsdelivr.net/gh/mikupeto/warp-script/files/netflix-verify/nf-linux-amd64
          curl https://purge.jsdelivr.net/gh/mikupeto/warp-script/files/netflix-verify/nf-linux-arm64
          curl https://purge.jsdelivr.net/gh/mikupeto/warp-script/files/netflix-verify/nf-linux-s390x