name: Fetch wgcf to latest version

on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Fetch wgcf to latest version
        run: |
          rm -f files/wgcf/wgcf-latest-linux-amd64 files/wgcf/wgcf-latest-linux-arm64 files/wgcf/wgcf-latest-linux-s390x files/wgcf/wgcf-fetchlog.txt
          actions_date=$(date)
          repo_last_ver=$(curl -Ls "https://api.github.com/repos/ViRb3/wgcf/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          repo_ver_name=$(curl -Ls "https://api.github.com/repos/ViRb3/wgcf/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed "s/v//g")
          wget https://github.com/ViRb3/wgcf/releases/download/$repo_last_ver/wgcf_"$repo_ver_name"_linux_amd64 -O files/wgcf/wgcf-latest-linux-amd64
          wget https://github.com/ViRb3/wgcf/releases/download/$repo_last_ver/wgcf_"$repo_ver_name"_linux_arm64 -O files/wgcf/wgcf-latest-linux-arm64
          wget https://github.com/ViRb3/wgcf/releases/download/$repo_last_ver/wgcf_"$repo_ver_name"_linux_s390x -O files/wgcf/wgcf-latest-linux-s390x
          cat <<EOF > files/wgcf/wgcf-fetchlog.txt
          # wgcf fetch log generated by GitHub Actions
          Last Version: $repo_last_ver
          Fetch Date: $actions_date
          EOF
      - name: Upload to GitHub
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "CI: Auto fetch wgcf at $(date +"%m-%d %H:%M")"
          git push
      - name: Refresh Jsdelivr cache
        run: |
          curl https://purge.jsdelivr.net/gh/mikupeto/warp-script/files/wgcf/wgcf-latest-linux-amd64
          curl https://purge.jsdelivr.net/gh/mikupeto/warp-script/files/wgcf/wgcf-latest-linux-arm64
          curl https://purge.jsdelivr.net/gh/mikupeto/warp-script/files/wgcf/wgcf-latest-linux-s390x