name: Fetch wireproxy to latest version

on:
  workflow_dispatch:
  schedule:
    - cron: "00 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - name: Fetch wireproxy to latest version
        run: |
          rm -f files/wireproxy/wireproxy-latest-linux-amd64 files/wireproxy/wireproxy-latest-linux-arm64 files/wireproxy/wireproxy-latest-linux-s390x files/wireproxy/wireproxy-fetchlog.txt
          actions_date=$(date)
          repo_last_ver=$(curl -Ls "https://api.github.com/repos/octeep/wireproxy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          wget -N https://github.com/octeep/wireproxy/releases/download/$repo_last_ver/wireproxy_linux_amd64.tar.gz
          tar -zxvf wireproxy_linux_amd64.tar.gz
          rm -f wireproxy_linux_amd64.tar.gz
          mv -f wireproxy files/wireproxy/wireproxy-latest-linux-amd64
          wget -N https://github.com/octeep/wireproxy/releases/download/$repo_last_ver/wireproxy_linux_arm64.tar.gz
          tar -zxvf wireproxy_linux_arm64.tar.gz
          rm -f wireproxy_linux_arm64.tar.gz
          mv -f wireproxy files/wireproxy/wireproxy-latest-linux-arm64
          wget -N https://github.com/octeep/wireproxy/releases/download/$repo_last_ver/wireproxy_linux_s390x.tar.gz
          tar -zxvf wireproxy_linux_s390x.tar.gz
          rm -f wireproxy_linux_s390x.tar.gz
          mv -f wireproxy files/wireproxy/wireproxy-latest-linux-s390x
          cat <<EOF > files/wireproxy/wireproxy-fetchlog.txt
          # wireproxy fetch log generated by GitHub Actions
          Last Version: $repo_last_ver
          Fetch Date: $actions_date
          EOF
      - name: Upload to GitHub
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "CI: Auto fetch wireproxy at $(date +"%m-%d %H:%M")"
          git push